services:
  vaults_service_postgres:
    image: postgres:16.1-bullseye
    restart: unless-stopped
    volumes:
      - vaults_service_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${VAULTS_SERVICE_POSTGRES_DB_NAME}
      - POSTGRES_USER=${VAULTS_SERVICE_POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${VAULTS_SERVICE_POSTGRES_DB_PASSWORD}
    ports:
      - 8280:5432
    networks:
      - vaults_services_network
  vaults_service:
    build: vaults_service
    restart: unless-stopped
    volumes:
      - ./vaults_service:/usr/src/vaults_service
    env_file:
      - ./vaults_service/.env
    ports:
      - 8200:8000
    depends_on:
      - vaults_service_postgres
    networks:
      - vaults_services_network
      - papper-backend
    command: >
      sh -c "alembic upgrade head && 
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/vaults_service/uvicorn_logging.conf"

volumes:
  vaults_service_postgres_data:

networks:
  vaults_services_network:
    name: vaults_services_network
  papper-backend:
    name: papper-backend
    external: true
